Cylon = TASK, { TASK } ;   

TASK = "TASK", Identifier, "{", Command, [TaskBody], "}"  ;

TaskBody =  [ScheduleStmt], [Dependency], [Condition] ;

Command = RunCmd | MoveCmd | GenerateCmd | ExportCmd | SendCmd ;

RunCmd = "RUN", String ;

MoveCmd = "MOVE", String, "TO", String ;

SendCmd = "SEND", String, "TO", String ;

GenerateCmd = "GENERATE", String ;

ExportCmd = "EXPORT", String ;

Dependency = ("AFTER" | "BEFORE"), Identifier ;

Condition = "IF", ("SUCCESS" | "FAILED") ;

ScheduleStmt = ScheduleTime, "AT", TIME ;

ScheduleTime = "EVERY", "DAY" | ("EVERY", "WEEK", "ON", DayOfWeek) ;

DayOfWeek = "SUNDAY" | "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" ;

Identifier = Letter, { Letter | Digit } ; 

String = '"', { Character }, '"' ; 

TIME = Digit, Digit, ":", Digit, Digit ; 

Letter      = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" ; 

Digit       = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ; 

Character = ? any printable character except double quote ? ;

