//Parser Rules
<Cylon> ::= <TASK> <TASK_LIST>

<TASK_LIST> ::= <TASK> <TASK_LIST> | ε


<TASK> ::= "TASK" <Identifier> "{" <Command> <TaskBodyOpt> "}"

<TaskBodyOpt> ::= <TaskBody> | ε


<TaskBody> ::= <ScheduleOpt> <DependencyOpt> <ConditionOpt>

<ScheduleOpt> ::= <ScheduleStmt> | ε
<DependencyOpt> ::= <Dependency> | ε
<ConditionOpt> ::= <Condition> | ε


<Command> ::= <RunCmd> | <MoveCmd> | <GenerateCmd> | <ExportCmd> | <SendCmd>


<RunCmd> ::= "RUN" <String>

<MoveCmd> ::= "MOVE" <String> "TO" <String>

<SendCmd> ::= "SEND" <String> "TO" <String>

<GenerateCmd> ::= "GENERATE" <String>

<ExportCmd> ::= "EXPORT" <String>


<Dependency> ::= "AFTER" <Identifier> | "BEFORE" <Identifier>

<Condition> ::= "IF" <ConditionType>

<ConditionType> ::= "SUCCESS" | "FAILED"


<ScheduleStmt> ::= <ScheduleTime> "AT" <TIME>

<ScheduleTime> ::= "EVERY" "DAY"
                 | "EVERY" "WEEK" "ON" <DayOfWeek>


<DayOfWeek> ::= "SUNDAY" | "MONDAY" | "TUESDAY" | "WEDNESDAY"
              | "THURSDAY" | "FRIDAY" | "SATURDAY"


//Lexer Rules
<Identifier> ::= <Letter> <IdentifierTail>

<IdentifierTail> ::= <LetterOrDigit> <IdentifierTail> | ε

<LetterOrDigit> ::= <Letter> | <Digit>


<String> ::= '"' <StringContent> '"'

<StringContent> ::= <Character> <StringContent> | ε


<TIME> ::= <Digit> <Digit> ":" <Digit> <Digit>


<Letter> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M"
           | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
           | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m"
           | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"


<Digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"


<Character> ::= any printable character except '"'