Cylon = TASK, { TASK } ;   

TASK = "TASK", Identifier, "{", Command, [TaskBody] "}"  ;

TaskBody =  [ScheduleStmt], [Dependency], [Condition] ;

Command = RunCmd | MoveCmd | GenerateCmd | ExportCmd | SendCmd ;

RunCmd = "RUN", String ;

MoveCmd = "MOVE", String, "TO", String ;

SendCmd = "SEND", String, "TO", String ;

GenerateCmd = "GENERATE", String ;

ExportCmd = "EXPORT", String ;

Dependency = ("AFTER" | "BEFORE"), Identifier ;

Condition = "IF", ("SUCCESS" | "FAILED") ;

ScheduleStmt = ScheduleTime, "AT", TIME ;

ScheduleTime = "EVERY DAY" | ("EVERY WEEK", "ON", DayOfWeek) ;

DayOfWeek = "SUNDAY" | "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" ;

Identifier = Letter, { Letter | Digit } ; 

String = '"', { Character }, '"' ; 

Time = Digit, Digit, ":", Digit, Digit ; 

Letter      = "A" | ... | "Z" | "a" | ... | "z" ; 

Digit       = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ; 

Character = ? any printable character except double quote ? ;

