Cylon =TASK, { TASK } ;

TASK = "TASK", Identifier, "{", Command, ScheduleTime, ScheduleStmt, "}"  ;

Command = "RUN" | "MOVE" | "GENERATE" | "EXPORT" | "SEND", String ;

ScheduleTime = "EVERY DAY" | "AFTER" | "BEFORE" | 

ScheduleStmt = ScheduleTime, "AT", TIME ;

Identifier = Letter, { Letter | Digit } ;

String = '"', { Character }, '"' ;

Time = Digit, Digit, ":", Digit, Digit ;

Letter      = "A" | ... | "Z" | "a" | ... | "z" ;

Digit       = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

Character   = ? any character except " ? ;

- TASK
- RUN
- EVERY
- DAY
- AT
- BEFORE
- AFTER
- SUCCESS
- FAILED
- IF
- WEEK
- ON
- TIME

